HardwareStore/Controllers/CategoryController.cs
using FluentValidation;
using FluentValidation.Results;
using HardwareStore.Models;
using HardwareStore.Repositories.Categories;
using HardwareStore.Validations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HardwareStore.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IValidator<Category> _validator;

        public CategoryController(ICategoryRepository categoryRepository, IValidator<Category> validator)
        {
            _categoryRepository = categoryRepository;
            _validator = validator;
        }

        // GET: CategoryController
        [Authorize(Roles = "Administrador, SoloLectura, Inventario")]
        public async Task<ActionResult> Index()
        {
            var categorys = await _categoryRepository.GetAllCategoryAsync();

            return View(categorys);
        }

        // GET: CategoryController/Create
        [Authorize(Roles = "Administrador, Inventario")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Inventario")]
        public async Task<ActionResult> Create(Category category)
        {
            try
            {
                ValidationResult validationResult = await _validator.ValidateAsync(category);

                if (!validationResult.IsValid)
                {
                    validationResult.AddToModelState(this.ModelState);

                    return View(category);
                }

                // Comprobar si ya existe un producto con el mismo nombre
                if (await _categoryRepository.CategoryNameExistsAsync(category.CategoryName))
                {
                    ModelState.AddModelError("CategoryName", "Ya existe una categoria con este nombre.");

                    return View(category);
                }

                // Agregar el producto si no existe otro con el mismo nombre
                await _categoryRepository.AddCategoryAsync(category);

                TempData["addCategory"] = "Categoria agregada con exito";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                return View(category);
            }
        }

        // GET: CategoryController/Edit/5
        [Authorize(Roles = "Administrador, Inventario")]
        public async Task<ActionResult> Edit(int id)
        {
            var categorys = await _categoryRepository.GetByIdCategoryAsync(id);

            if (categorys == null)
                return NotFound();

            return View(categorys);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Inventario")]
        public async Task<ActionResult> Edit(Category category)
        {
            try
            {
                await _categoryRepository.EditCategoryAsync(category);

                TempData["editCategory"] = "Categoria editada con exito";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                return View(category);
            }
        }

        // GET: CategoryController/Delete/5
        [Authorize(Roles = "Administrador, Inventario")]
        public async Task<ActionResult> Delete(int id)
        {
            var categorys = await _categoryRepository.GetByIdCategoryAsync(id);

            if (categorys == null)
                return NotFound();

            return View(categorys);
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Inventario")]
        public async Task<ActionResult> Delete(Category category)
        {
            try
            {
                await _categoryRepository.DeleteCategoryAsync(category.Id);

                TempData["deleteCategory"] = "Categoria eliminado con exito";

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["message"] = "No se pudo eliminar la categoria";

                return RedirectToAction(nameof(Index));
            }
        }

    }
}

HardwareStore/Controllers/RoleController.cs
using HardwareStore.Models;
using HardwareStore.Repositories.Roles;
using HardwareStore.Validations;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;


namespace HardwareStore.Controllers
{
    public class RoleController : Controller
    {
        private readonly IRoleRepository _roleRepository;
        private readonly IValidator<Role> _validator;

        public RoleController(IRoleRepository roleRepository, IValidator<Role> validator)
        {
            _roleRepository = roleRepository;
            _validator = validator;
        }

        [Authorize(Roles = "Administrador, SoloLectura")]
        public async Task<IActionResult> Index()
        {

            var roles = await _roleRepository.GetAllAsync();

            return View(roles);
        }

        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<ActionResult> Create(Role role)
        {

            try
            {
                FluentValidation.Results.ValidationResult validationResult = await _validator.ValidateAsync(role);

                if (!validationResult.IsValid)
                {
                    validationResult.AddToModelState(ModelState);
                    return View(role);
                }

                await _roleRepository.AddAsync(role);

                TempData["addRole"] = "Rol agregado correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(role);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public async Task<ActionResult> Edit(int id)
        {
            var role = await _roleRepository.GetByIdAsync(id);

            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<ActionResult> Edit(Role role)
        {
            try
            {
                FluentValidation.Results.ValidationResult validationResult = await _validator.ValidateAsync(role);

                if (!validationResult.IsValid)
                {
                    validationResult.AddToModelState(ModelState);
                    return View(role);
                }

                await _roleRepository.EditAsync(role);

                TempData["editRole"] = "Rol editado correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(role);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public async Task<ActionResult> Delete(int id)
        {
            var login = await _roleRepository.GetByIdAsync(id);

            if (login == null)
            {
                return NotFound();
            }

            return View(login);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<ActionResult> Delete(Role role)
        {
            try
            {
                await _roleRepository.DeleteAsync(role.Id);

                TempData["deleteRole"] = "Rol eliminado correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = "No se puede eliminar el rol";

                return RedirectToAction(nameof(Index));
            }
        }
    }
}

HardwareStore/Controllers/SaleController.cs
using FluentValidation;
using FluentValidation.Results;
using HardwareStore.Models;
using HardwareStore.Repositories.Sales;
using HardwareStore.Services.Email;
using HardwareStore.Validations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace HardwareStore.Controllers
{
    public class SaleController : Controller
    {
        private readonly ISaleRepository _saleRepository;
        private readonly IValidator<Sale> _validator;
        private readonly IValidator<Customer> _customerValidator;

        private readonly IEmailService _emailService;

        public SaleController(ISaleRepository saleRepository, IValidator<Sale> validator, IValidator<Customer> customerValidator,IEmailService emailService)
        {
            _saleRepository = saleRepository;

            _validator = validator;

            _customerValidator = customerValidator;

            _emailService = emailService;
        }

        // GET: SaleController
        [Authorize(Roles = "Administrador, Inventario, Vendedor, SoloLectura, Marketing")]
        public async Task<ActionResult> Index()
        {
            return View(await _saleRepository.GetAllAsync());
        }

        // GET: SaleController/Details/5
        [Authorize(Roles = "Administrador, Inventario, Vendedor, SoloLectura")]
        public async Task<ActionResult> Details(int id)
        {
            var sale = await _saleRepository.GetSaleByIdAsync(id);

            sale.SaleDetails = (List<SaleDetail>)await _saleRepository.GetSaleDetailsByIdAsync(id);

            return View(sale);
        }

        [HttpPost]
        [Authorize(Roles = "Administrador, Inventario, Vendedor")]
        public async Task<ActionResult> Details()
        {
            return View();
        }

        // metodo para la peticion ajax, envia los detalles del producto seleccionado a la vista
        [HttpGet]
        [Authorize(Roles = "Administrador, Inventario, Vendedor, SoloLectura")]
        public async Task<IActionResult> SearchProductById(int id) // recibe el id del producto
        {
            try
            {
                var product = await _saleRepository.GetProductByIdAsync(id); // busca el productopor id

                if (product == null)
                {
                    return NotFound();
                }

                return Json(product); // retorna los datos del producto en formato Json
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Internal server error");
            }
        }


        // GET: SaleController/Create
        [Authorize(Roles = "Administrador, Inventario, Vendedor, SoloLectura")]
        public async Task<ActionResult> Create()
        {
            await ViewBagLists();

            var sale = new Sale
            {
                SaleDetails = new List<SaleDetail>()
            };

            return View(sale);
        }


        // POST: SaleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Inventario, Vendedor")]
        public async Task<ActionResult> Create(Sale sale)
        {
            var employeeId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (employeeId == null)
            {
                TempData["message"] = "No se encrontro el Empleado";

                await ViewBagLists();

                return View(sale);
            }

            sale.EmployeeID = Int32.Parse(employeeId);

            if (sale.SaleDetails == null)
            {
                TempData["message"] = "Debe Agregar Almenos 1 Producto";

                await ViewBagLists();

                return View(sale);
            }

            try
            {
                ValidationResult validationResult = await _validator.ValidateAsync(sale);

                if (!validationResult.IsValid)
                {
                    validationResult.AddToModelState(this.ModelState);

                    await ViewBagLists();

                    return View(sale);
                }

                await _saleRepository.AddAsync(sale);

                var customer = await _saleRepository.GetCustomerByIdAsync(sale.CustomerID);

                Dictionary<string, string> data = new Dictionary<string, string>
                {
                    { "Subject", "Factura de Compra" },
                    { "RecepientName",(customer?.FirstName + ' ' + customer?.LastName).ToString() },
                    { "EmailTo", customer.Email },
                    { "Address", customer.Address  },
                    { "City", customer.City }
                };

                _emailService.SendEmail(data, sale.SaleDetails.ToList());

                TempData["addSale"] = "Se registro la venta correctamente";

                return RedirectToAction(nameof(Index));

            }
            catch
            {
                await ViewBagLists();

                return View(sale);
            }
        }

        // POST:  ClientController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Inventario, Vendedor")]
        public async Task<ActionResult> CreateCustomer(Customer customer)
        {
            try
            {
                ValidationResult validationResult = await _customerValidator.ValidateAsync(customer);

                if (!validationResult.IsValid)
                {
                    return BadRequest(validationResult.Errors); // Devuelve errores de validación como JSON
                }

                int customerID = await _saleRepository.AddCustomerAsync(customer);

                return Json(new
                {
                    success = true,
                    message = "Cliente agregado con éxito",
                    customer = new
                    {
                        Id = customerID,
                        customerName = customer.FirstName + ' ' + customer.LastName,
                        customer.Phone
                    }
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        private async Task ViewBagLists()
        {
            var products = await _saleRepository.GetAllProductsAsync();
            ViewBag.Products = new SelectList(products, nameof(Product.Id), nameof(Product.ProductName));

            var customers = await _saleRepository.GetAllCustomersAsync();
            ViewBag.Customers = new SelectList(customers, nameof(Customer.Id), nameof(Customer.CustomerName));

            var employees = await _saleRepository.GetAllEmployeesAsync();
            ViewBag.Employees = new SelectList(employees, nameof(Employee.Id), nameof(Employee.EmployeeName));
        }

    }
}

HardwareStore/Views/Shared/Partials/_CustomerModalForSales.cshtml
<!-- Modal -->
<div class="modal fade" id="modalCustomer" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregar Cliente</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-controller="Sale" asp-action="CreateCustomer" id="form-add-customer" method="post">
                    @Html.AntiForgeryToken()
                    <div  class="text-danger"></div>
                    <div class="form-group">
                        <label  class="control-label">Nombres</label><b class="text-danger">*</b>
                        <input name="FirstName" class="form-control" required />
                        <span  class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  class="control-label">Apellidos</label><b class="text-danger"> *</b>
                        <input name="LastName" class="form-control" required />
                        <span class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  class="control-label">Email</label>
                        <input name="Email" class="form-control" />
                        <span  class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Telefono</label><b class="text-danger"> *</b>
                        <input name="Phone" class="form-control" />
                        <span  class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  class="control-label">Direccion</label><b class="text-danger"> *</b>
                        <input name="Address" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  class="control-label">Ciudad</label><b class="text-danger"> *</b>
                        <input name="City" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Guardar <i class="lni lni-save"></i></button>
                        <a class="btn btn-primary" asp-action="Index">Volver a la lista <i class="lni lni-arrow-left"></i></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('form-add-customer').addEventListener('submit', async function (e) {
    e.preventDefault();

    const form = e.target;
    const formData = new FormData(form);

    console.log(formData)

    const token = formData.get('__RequestVerificationToken');

    try {
        const response = await fetch(form.action, {
            method: 'POST',
            headers: {
                'RequestVerificationToken': token
            },
            body: formData
        });

        const result = await response.json();

        if (response.ok && result.success) {
            alert(result.message);

            // Opcional: agregar nuevo cliente al dropdown
            const select = document.getElementById('customersSearch');
            const option = new Option(result.customer.customerName, result.customer.id, true, true);
            select.add(option);

            // Cerrar modal (si estás usando Bootstrap)
            const modal = bootstrap.Modal.getInstance(document.getElementById('modalCustomer'));
            modal.hide();

            // Resetear formulario
            form.reset();
        } else {
            alert("Error al agregar cliente.");
            console.log(result);
        }

    } catch (err) {
        console.error('Error:', err);
        alert('Error en el servidor');
    }
});
</script>

HardwareStore/Views/Shared/Partials/_Footer.cshtml
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 order-last order-md-first">
                <div class="copyright text-center text-md-start">
                    <p class="text-sm">
                        Designed and Developed by Ferreteria "El Maestro"
                    </p>
                </div>
            </div>
            <!-- end col-->
            <div class="col-md-6">
                <div class="terms d-flex justify-content-center justify-content-md-end">
                    <a href="#0" class="text-sm">Term & Conditions</a>
                    <a href="#0" class="text-sm ml-15">Privacy & Policy</a>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</footer>

HardwareStore/Views/Shared/Partials/_Header.cshtml
@{
    var userName = User.FindFirst(System.Security.Claims.ClaimTypes.Name)?.Value;
    var role = User.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value;
}﻿
<header class="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-5 col-md-5 col-6">
                <div class="header-left d-flex align-items-center">
                    <div class="menu-toggle-btn mr-15">
                        <button id="menu-toggle" class="main-btn primary-btn btn-hover">
                            <i class="lni lni-chevron-left me-2"></i> Menu
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-lg-7 col-md-7 col-6">
                <div class="header-right">

                    <!-- profile start -->
                    <div class="profile-box ml-15">
                        <button class="dropdown-toggle bg-transparent border-0" type="button" id="profile"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="profile-info">
                                <div class="info">
                                    <div class="image">
                                        <img src="~/images/profile/profile-image.png" alt="" />
                                    </div>
                                    <div>
                                        <h6 class="fw-500">@userName</h6>
                                        <p>@role</p>
                                    </div>
                                </div>
                            </div>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profile">
                            <li class="divider"></li>
                            <li>
                                <a asp-area="" asp-controller="Login" asp-action="Logout"><i class="lni lni-exit"></i> Cerrar sesion</a>
                            </li>
                        </ul>
                    </div>
                    <!-- profile end -->
                </div>
            </div>
        </div>
    </div>
</header>

HardwareStore/Views/Shared/Partials/_SideBar.cshtml
<aside class="sidebar-nav-wrapper">
    <div class="navbar-logo">
        <a asp-action="Index" asp-controller="Home">
            <img src="~/images/logo/HardwareStoreLogo.png" alt="logo" width="190px" height="200px" />
        </a>
    </div>
    <nav class="sidebar-nav">
        <ul>
            <li class="nav-item">
                <span class="text px-4"><strong>Ferreteria "El Maestro"</strong></span>
            </li>
            <li class="nav-item nav-item-has-children">
                <a href="#0"
                   class=""
                   data-bs-toggle="collapse"
                   data-bs-target="#ddmenu_2"
                   aria-controls="ddmenu_2"
                   aria-expanded="false"
                   aria-label="Toggle navigation">
                    <span class="icon">
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8.74999 18.3333C12.2376 18.3333 15.1364 15.8128 15.7244 12.4941C15.8448 11.8143 15.2737 11.25 14.5833 11.25H9.99999C9.30966 11.25 8.74999 10.6903 8.74999 10V5.41666C8.74999 4.7263 8.18563 4.15512 7.50586 4.27556C4.18711 4.86357 1.66666 7.76243 1.66666 11.25C1.66666 15.162 4.83797 18.3333 8.74999 18.3333Z" />
                            <path d="M17.0833 10C17.7737 10 18.3432 9.43708 18.2408 8.75433C17.7005 5.14918 14.8508 2.29947 11.2457 1.75912C10.5629 1.6568 10 2.2263 10 2.91665V9.16666C10 9.62691 10.3731 10 10.8333 10H17.0833Z" />
                        </svg>
                    </span>
                    <span class="text">DashBoard</span>
                </a>
                <ul id="ddmenu_2" class="collapse show dropdown-nav">
                    @if (User.IsInRole("Administrador") || User.IsInRole("SoloLectura")){
                        <li>
                            <a asp-controller="Role"
                               asp-action="Index">
                                <i class="lni lni-notepad text-bold"></i> Roles
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Employee"
                               asp-action="Index">
                                <i class="lni lni-user text-bold"></i> Empleados
                            </a>
                        </li>
                    }

                    @if (User.IsInRole("Administrador") || User.IsInRole("Inventario") || User.IsInRole("SoloLectura"))
                    {
                        <li>
                            <a asp-controller="Supplier"
                               asp-action="Index">
                                <i class="lni lni-delivery text-bold"></i> Proveedores
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Product"
                               asp-action="Index">
                                <i class="lni lni-briefcase-alt text-bold"></i> Productos
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Category"
                               asp-action="Index">
                                <i class="lni lni-tag text-bold"></i> Categorias
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("Administrador") || User.IsInRole("Inventario") || User.IsInRole("SoloLectura") || User.IsInRole("Vendedor") || User.IsInRole("Marketing"))
                    {
                        <li>
                            <a asp-controller="Customer"
                               asp-action="Index">
                                <i class="lni lni-customer text-bold"></i> Clientes
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Sale"
                               asp-action="Index">
                                <i class="lni lni-cart-full text-bold"></i> Ventas
                            </a>
                        </li>
                    }
                </ul>
            </li>
        </ul>
    </nav>
</aside>